ci: Delete PR description update GH action (#268)
## Description:
<!-- Describe this change, how it works, and the motivation behind it.
-->
PR descripton update hasn't addded much value and requires an elevated
token that is not present for bots and external contributors, see:


https://github.com/kurtosis-tech/kurtosis/actions/runs/4461198457/jobs/7847386969?pr=240
```
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```

## Is this change user facing?
<!-- A user facing change is one that you should expect a day-to-day
user to encounter or if the change requires user-action upon or before
upgrading. If in doubt, select "Yes" -->
* [ ] Yes
* [X] No

<!-- If yes, please add the `user facing` label to this Pull Request -->

## References (if applicable):
<!-- Add relevant Github Issues, Discord threads, or other helpful
information. -->