fix: Address flakiness of extractor test (#510)
## Description:
`TestExtractor_Success` test shows flakiness due to the divergence on
how `starlark.Dict` is represented internally between test runs. Despite
working most of the time, by exhaustively running the test >100 times,
you get the following error:
```
extractor_test.go:42: 
        	Error Trace:	/Volumes/git/kurtosis/core/server/api_container/server/startosis_engine/recipe/extractor_test.go:42
        	Error:      	Not equal: 
        	            	expected: &starlark.Dict{ht:starlark.hashtable{table:[]starlark.bucket{starlark.bucket{entries:[8]starlark.entry{starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x9d275898, key:"another_key", value:starlark.Int{impl:(starlark.intImpl)(0x2ffffffff)}, next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(0x140002b49c8)}, starlark.entry{hash:0x6815c86c, key:"key", value:"value", next:(*starlark.entry)(0x140002b4968), prevLink:(**starlark.entry)(0x140002b49e8)}}, next:(*starlark.bucket)(nil)}}, bucket0:[1]starlark.bucket{starlark.bucket{entries:[8]starlark.entry{starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x9d275898, key:"another_key", value:starlark.Int{impl:(starlark.intImpl)(0x2ffffffff)}, next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(0x140002b49c8)}, starlark.entry{hash:0x6815c86c, key:"key", value:"value", next:(*starlark.entry)(0x140002b4968), prevLink:(**starlark.entry)(0x140002b49e8)}}, next:(*starlark.bucket)(nil)}}, len:0x2, itercount:0x0, head:(*starlark.entry)(0x140002b49a0), tailLink:(**starlark.entry)(0x140002b4990), frozen:false, _:starlark.noCopy{}}}
        	            	actual  : &starlark.Dict{ht:starlark.hashtable{table:[]starlark.bucket{starlark.bucket{entries:[8]starlark.entry{starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x6815c86c, key:"key", value:"value", next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(0x140002b4bc8)}, starlark.entry{hash:0x9d275898, key:"another_key", value:starlark.Int{impl:(starlark.intImpl)(0x2ffffffff)}, next:(*starlark.entry)(0x140002b4b68), prevLink:(**starlark.entry)(0x140002b4be8)}}, next:(*starlark.bucket)(nil)}}, bucket0:[1]starlark.bucket{starlark.bucket{entries:[8]starlark.entry{starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x0, key:starlark.Value(nil), value:starlark.Value(nil), next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(nil)}, starlark.entry{hash:0x6815c86c, key:"key", value:"value", next:(*starlark.entry)(nil), prevLink:(**starlark.entry)(0x140002b4bc8)}, starlark.entry{hash:0x9d275898, key:"another_key", value:starlark.Int{impl:(starlark.intImpl)(0x2ffffffff)}, next:(*starlark.entry)(0x140002b4b68), prevLink:(**starlark.entry)(0x140002b4be8)}}, next:(*starlark.bucket)(nil)}}, len:0x2, itercount:0x0, head:(*starlark.entry)(0x140002b4ba0), tailLink:(**starlark.entry)(0x140002b4b90), frozen:false, _:starlark.noCopy{}}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -48,2 +48,15 @@
        	            	      (starlark.entry) {
        	            	+      hash: (uint32) 1746258028,
        	            	+      key: (starlark.String) (len=3) "key",
        	            	+      value: (starlark.String) (len=5) "value",
        	            	+      next: (*starlark.entry)(<nil>),
        	            	+      prevLink: (**starlark.entry)({
        	            	+       hash: (uint32) 1746258028,
        	            	+       key: (starlark.String) (len=3) "key",
        	            	+       value: (starlark.String) (len=5) "value",
        	            	+       next: (*starlark.entry)(<nil>),
        	            	+       prevLink: (**starlark.entry)(<already shown>)
        	            	+      })
        	            	+     },
        	            	+     (starlark.entry) {
        	            	       hash: (uint32) 2636601496,
        	            	@@ -53,3 +66,9 @@
        	            	       },
        	            	-      next: (*starlark.entry)(<nil>),
        	            	+      next: (*starlark.entry)({
        	            	+       hash: (uint32) 1746258028,
        	            	+       key: (starlark.String) (len=3) "key",
        	            	+       value: (starlark.String) (len=5) "value",
        	            	+       next: (*starlark.entry)(<nil>),
        	            	+       prevLink: (**starlark.entry)(<already shown>)
        	            	+      }),
        	            	       prevLink: (**starlark.entry)({
        	            	@@ -60,29 +79,6 @@
        	            	        },
        	            	-       next: (*starlark.entry)(<nil>),
        	            	-       prevLink: (**starlark.entry)(<already shown>)
        	            	-      })
        	            	-     },
        	            	-     (starlark.entry) {
        	            	-      hash: (uint32) 1746258028,
        	            	-      key: (starlark.String) (len=3) "key",
        	            	-      value: (starlark.String) (len=5) "value",
        	            	-      next: (*starlark.entry)({
        	            	-       hash: (uint32) 2636601496,
        	            	-       key: (starlark.String) (len=11) "another_key",
        	            	-       value: (starlark.Int) {
        	            	-        impl: (starlark.intImpl) 0x2ffffffff
        	            	-       },
        	            	-       next: (*starlark.entry)(<nil>),
        	            	-       prevLink: (**starlark.entry)(<already shown>)
        	            	-      }),
        	            	-      prevLink: (**starlark.entry)({
        	            	-       hash: (uint32) 1746258028,
        	            	-       key: (starlark.String) (len=3) "key",
        	            	-       value: (starlark.String) (len=5) "value",
        	            	        next: (*starlark.entry)({
        	            	-        hash: (uint32) 2636601496,
        	            	-        key: (starlark.String) (len=11) "another_key",
        	            	-        value: (starlark.Int) {
        	            	-         impl: (starlark.intImpl) 0x2ffffffff
        	            	-        },
        	            	+        hash: (uint32) 1746258028,
        	            	+        key: (starlark.String) (len=3) "key",
        	            	+        value: (starlark.String) (len=5) "value",
        	            	         next: (*starlark.entry)(<nil>),
        	            	@@ -143,2 +139,15 @@
        	            	      (starlark.entry) {
        	            	+      hash: (uint32) 1746258028,
        	            	+      key: (starlark.String) (len=3) "key",
        	            	+      value: (starlark.String) (len=5) "value",
        	            	+      next: (*starlark.entry)(<nil>),
        	            	+      prevLink: (**starlark.entry)({
        	            	+       hash: (uint32) 1746258028,
        	            	+       key: (starlark.String) (len=3) "key",
        	            	+       value: (starlark.String) (len=5) "value",
        	            	+       next: (*starlark.entry)(<nil>),
        	            	+       prevLink: (**starlark.entry)(<already shown>)
        	            	+      })
        	            	+     },
        	            	+     (starlark.entry) {
        	            	       hash: (uint32) 2636601496,
        	            	@@ -148,3 +157,9 @@
        	            	       },
        	            	-      next: (*starlark.entry)(<nil>),
        	            	+      next: (*starlark.entry)({
        	            	+       hash: (uint32) 1746258028,
        	            	+       key: (starlark.String) (len=3) "key",
        	            	+       value: (starlark.String) (len=5) "value",
        	            	+       next: (*starlark.entry)(<nil>),
        	            	+       prevLink: (**starlark.entry)(<already shown>)
        	            	+      }),
        	            	       prevLink: (**starlark.entry)({
        	            	@@ -155,29 +170,6 @@
        	            	        },
        	            	-       next: (*starlark.entry)(<nil>),
        	            	-       prevLink: (**starlark.entry)(<already shown>)
        	            	-      })
        	            	-     },
        	            	-     (starlark.entry) {
        	            	-      hash: (uint32) 1746258028,
        	            	-      key: (starlark.String) (len=3) "key",
        	            	-      value: (starlark.String) (len=5) "value",
        	            	-      next: (*starlark.entry)({
        	            	-       hash: (uint32) 2636601496,
        	            	-       key: (starlark.String) (len=11) "another_key",
        	            	-       value: (starlark.Int) {
        	            	-        impl: (starlark.intImpl) 0x2ffffffff
        	            	-       },
        	            	-       next: (*starlark.entry)(<nil>),
        	            	-       prevLink: (**starlark.entry)(<already shown>)
        	            	-      }),
        	            	-      prevLink: (**starlark.entry)({
        	            	-       hash: (uint32) 1746258028,
        	            	-       key: (starlark.String) (len=3) "key",
        	            	-       value: (starlark.String) (len=5) "value",
        	            	        next: (*starlark.entry)({
        	            	-        hash: (uint32) 2636601496,
        	            	-        key: (starlark.String) (len=11) "another_key",
        	            	-        value: (starlark.Int) {
        	            	-         impl: (starlark.intImpl) 0x2ffffffff
        	            	-        },
        	            	+        hash: (uint32) 1746258028,
        	            	+        key: (starlark.String) (len=3) "key",
        	            	+        value: (starlark.String) (len=5) "value",
        	            	         next: (*starlark.entry)(<nil>),
        	            	@@ -195,11 +187,11 @@
        	            	   head: (*starlark.entry)({
        	            	-   hash: (uint32) 1746258028,
        	            	-   key: (starlark.String) (len=3) "key",
        	            	-   value: (starlark.String) (len=5) "value",
        	            	+   hash: (uint32) 2636601496,
        	            	+   key: (starlark.String) (len=11) "another_key",
        	            	+   value: (starlark.Int) {
        	            	+    impl: (starlark.intImpl) 0x2ffffffff
        	            	+   },
        	            	    next: (*starlark.entry)({
        	            	-    hash: (uint32) 2636601496,
        	            	-    key: (starlark.String) (len=11) "another_key",
        	            	-    value: (starlark.Int) {
        	            	-     impl: (starlark.intImpl) 0x2ffffffff
        	            	-    },
        	            	+    hash: (uint32) 1746258028,
        	            	+    key: (starlark.String) (len=3) "key",
        	            	+    value: (starlark.String) (len=5) "value",
        	            	     next: (*starlark.entry)(<nil>),
```

After this PR, we rely on both Starlark method to assert equality,
removing the dependence of the representation of the dict.

## Is this change user facing?
NO
<!-- If yes, please add the "user facing" label to the PR -->
<!-- If yes, don't forget to include docs changes where relevant -->

## References (if applicable):
<!-- Add relevant Github Issues, Discord threads, or other helpful
information. -->