fix(ci): upgrade rust to 1.88 (#2823)
## Description
Old rust version was causing rust sdk publish step to fail due to:

```
error: failed to parse manifest at /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/home-0.5.12/Cargo.toml 

Caused by: feature edition2024 is required 

The package requires the Cargo feature called edition2024, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)). Consider trying a newer version of Cargo (this may require the nightly release). See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```
I reproduced this issue locally running rust 1.81 and verified that
upgrading to 1.88 fixes the issue using a local `cargo build` and `cargo
publish --dry-run`.