fix: Fix TestStarlarkRemotePackage E2E test to reflect new quickstart (#773)
## Description:
<!-- Describe this change, how it works, and the motivation behind it.
-->
`TestStarlarkRemotePackage` is failing with message

```
--- FAIL: TestStartosisSubpackageTestSuite (38.49s)
    --- FAIL: TestStartosisSubpackageTestSuite/TestStarlarkRemotePackage (11.18s)
        startosis_remote_subpackage_test.go:31: 
            	Error Trace:	/home/circleci/project/internal_testsuites/golang/testsuite/startosis_subpackage_test/startosis_remote_subpackage_test.go:31
            	Error:      	Not equal: 
            	            	expected: 22
            	            	actual  : 4
            	Test:       	TestStartosisSubpackageTestSuite/TestStarlarkRemotePackage
```

This is due to our recent change to `awesome-kurtosis/quickstart`
package

Link:
https://app.circleci.com/pipelines/github/kurtosis-tech/kurtosis/4176/workflows/7d44b594-7005-4736-883f-5fe2b40aff75/jobs/52308

## Is this change user facing?
NO
<!-- If yes, please add the "user facing" label to the PR -->
<!-- If yes, don't forget to include docs changes where relevant -->

## References (if applicable):
<!-- Add relevant Github Issues, Discord threads, or other helpful
information. -->